### ISSUE TITLE
Colours for rabbits with abilities 121101067

### ISSUE THREAD

**Issue by muzafferbugra** [Bil481Project/rabbit-escape#2]
1) a yellow bag for the bridger to keep sections in
2)orange high vis vest for a digger (or possibly an orange hard hat with the ears poking through)
hat or vest for basher
3)bit stuck for blocker. possibly blue boots. or blue flags.
4)remove the light blue from the icon, so there is only the green brolly left.
5)red gloves and shoes for the climber.

perhaps change the blocker colour to red and give blockers a red stop sign. the climber would be blue. the general idea is to tie each ability icon to something of the same colour on the rabbit.

**Comment by cagdasgerede** [comment]
Buğra,

Burada yazan metni anlamıyorum. Düzeltin lütfen.
